services:
  inspection-service:
    container_name: inspection-service
    image: inspection-service
    restart: unless-stopped
    build:
      context: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8083:8083"
    env_file:
      - .env
    networks:
      - bridgecare-network

networks:
  bridgecare-network:
    external: true